v3.0.0 enhancements
lxghtless/occams-conf pull request #5
Opened 2019-12-05 06:18 UTC by lxghtless

### Enhancements, Features, Refactoring
- rework code base
- support loading config when used in global module (i.e. cli)
- support loading config from url
- support `get` functionality on config in addition to simply dotting access to property values.
- support manual init mode
	* when auto init is on, config is loaded asynchronously

2020-01-11 23:42 UTC, misterlantz requested changes
Just a grammar mistake in the readme

2020-01-11 23:42 UTC, misterlantz commented on readme.md
> +If and error resembling the following occurs, please check out the link below it.
`If an error`

2020-01-12 15:11 UTC, seesharpguy submitted a review, later dismissed
after initial npmrc settings issues, I could install and test locally. 👍 Looks good

2020-01-13 14:09 UTC, lxghtless commented on readme.md
> +If and error resembling the following occurs, please check out the link below it.
I'm bad at words.

2020-01-14 13:17 UTC, misterlantz approved these changes

2020-01-15 08:20 UTC, merged